#!/usr/bin/env ruby
# frozen_string_literal: true

require "fileutils"
require_relative "tool_registry"

module MessFormula
  SHA256 = /\A[0-9a-f]{64}\z/
  VERSION = /\A(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)\z/

  module_function

  def render(tool, version, arm64_sha, amd64_sha)
    metadata = ToolRegistry.fetch(tool)
    raise ArgumentError, "invalid stable semantic version" unless VERSION.match?(version)
    raise ArgumentError, "invalid arm64 SHA-256" unless SHA256.match?(arm64_sha)
    raise ArgumentError, "invalid amd64 SHA-256" unless SHA256.match?(amd64_sha)

    <<~RUBY
      class #{metadata.fetch(:class_name)} < Formula
        desc "#{metadata.fetch(:description)}"
        homepage "https://github.com/quality-gates/#{tool}"
        version "#{version}"
        license "MIT"

        on_macos do
          on_arm do
            url "https://github.com/quality-gates/#{tool}/releases/download/v#{version}/#{tool}_#{version}_darwin_arm64.tar.gz"
            sha256 "#{arm64_sha}"
          end

          on_intel do
            url "https://github.com/quality-gates/#{tool}/releases/download/v#{version}/#{tool}_#{version}_darwin_amd64.tar.gz"
            sha256 "#{amd64_sha}"
          end
        end

        def install
          bin.install "#{tool}"
          prefix.install "LICENSE"
        end

        test do
          assert_match "#{version}", shell_output("\#{bin}/#{tool} --version")
        end
      end
    RUBY
  end
end

if $PROGRAM_NAME == __FILE__
  abort "usage: #{$PROGRAM_NAME} TOOL VERSION ARM64_SHA256 AMD64_SHA256 OUTPUT" unless ARGV.length == 5

  tool, version, arm64_sha, amd64_sha, output = ARGV
  FileUtils.mkdir_p(File.dirname(output))
  File.write(output, MessFormula.render(tool, version, arm64_sha, amd64_sha))
end
